DROP TABLE IF EXISTS credits;

CREATE TABLE IF NOT EXISTS credits (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL UNIQUE,
    credit INT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP,
    renew_at TIMESTAMP,
    last_used_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_id ON credits(user_id);